on:
  workflow_dispatch:
  push:
    branches:
      - master
name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # token: ${{ secrets.PAT }}
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
      # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables

  build:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
